app/urls.py
from django.conf.urls import url
from . import views

app_name = 'app'

urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^create/$', views.Create.as_view(), name='create'),
    url(r'^update/(?P<pk>[0-9]+)/$', views.Update.as_view(), name='update'),
    url(r'^delete/(?P<pk>[0-9]+)/$', views.Delete.as_view(), name='delete'),
    url(r'^copy/(?P<pk>[0-9]+)/$', views.Copy.as_view(), name='copy'),
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app.urls')),
]

app/models.py
from django.db import models


class Post(models.Model):

    title = models.TextField('タイトル')

    def __str__(self):
        return self.title

app/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic
from .models import Post


class Index(generic.ListView):
    model = Post


class Create(generic.CreateView):
    model = Post
    fields = '__all__'
    success_url = reverse_lazy('app:index')


class Update(generic.UpdateView):
    model = Post
    fields = '__all__'
    success_url = reverse_lazy('app:index')


class Delete(generic.DeleteView):
    model = Post
    success_url = reverse_lazy('app:index')


class Copy(generic.UpdateView):
    model = Post
    fields = '__all__'
    success_url = reverse_lazy('app:index')

    def form_valid(self, form):
        post = form.save(commit=False)
        latest_pk = Post.objects.latest('pk').pk + 1
        post.pk = latest_pk
        post.save()
        return redirect(self.success_url)

app/templates/app/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  </head>
  <body>
      <div class="container">
            {% block content %}
            {% endblock %}
        </div>
 
    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/app/post_confirm_delete.html
{% extends 'app/base.html' %}
{% block content %}
    <form action="" method="POST">
        <p>{{ post.title }}を削除します。</p>
        {% csrf_token %}
        <button type="submit">削除</button>
    </form>
{% endblock %}

app/templates/app/post_form.html
{% extends 'app/base.html' %}
{% block content %}
    <form action="" method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit" name="action">送信</button>
    </form>
{% endblock %}

app/templates/app/post_list.html
{% extends 'app/base.html' %}
{% block content %}
<p><a href="{% url 'app:create' %}">新規作成</a></p>
    {% for post in post_list %}
        <p>
            {{ post.title }}
            <a href="{% url 'app:update' post.pk %}">更新</a> 
            <a href="{% url 'app:delete' post.pk %}">削除</a> 
            <a href="{% url 'app:copy' post.pk %}">記事の複製</a> 
        </p>
    {% endfor %}
{% endblock %}